[package]
name = "mc-bot-net"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
tokio-socks = "0.5"
rand = "0.8"
flate2 = "1.1.1"
aes = "0.8"
cfb8 = "0.8"
rsa = "0.9"
